print("This is my first block of code using Pycahrm")
print("It seems to be quiet user friendly")
print("Only thing i miss here is themes of vs code")
print("I'm still learning how to link my github to it ")
print("And i guess i have learnt it now")